name: Docker Image CI

on:
  push:

jobs:
  build:
    if: "startsWith(github.ref, 'refs/tags/')"
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.RENKU_DOCKER_USERNAME }}
          password: ${{ secrets.RENKU_DOCKER_PASSWORD }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: renku/rqmetrics
          # INFO: Tag with latest only on semver (non-pre-release) tag.
          # See https://github.com/docker/metadata-action#latest-tag for more details
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
          flavor: |
            latest=auto
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: startsWith(github.ref, 'refs/tags/')
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: "."
